services:
  pole-db:
    container_name: postgres-pole-metrics
    image: postgres
    environment:
      POSTGRES_DB: pole-metrics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
        - db-pole-metrics:/data/postgres
    ports:
        - "5432:5432"
    networks:
        - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db-pole-metrics: